"""Plot training curves from a Keras CSVLogger file."""

import argparse
from pathlib import Path

import matplotlib.pyplot as plt
import pandas as pd


def parse_args() -> argparse.Namespace:
    """Parse CLI arguments."""
    parser = argparse.ArgumentParser(description="Plot Keras training curves.")
    parser.add_argument(
        "--log_csv",
        type=str,
        default="artifacts/train_log.csv",
        help="Path to CSV log generated by tf.keras.callbacks.CSVLogger.",
    )
    parser.add_argument(
        "--metric",
        type=str,
        default="loss",
        help="Metric prefix to plot (e.g., loss, acc, auc, pr_auc, precision, recall).",
    )
    return parser.parse_args()


def main() -> None:
    """Render train/validation curves for a selected metric."""
    args = parse_args()
    csv_path = Path(args.log_csv)
    if not csv_path.exists():
        raise FileNotFoundError(f"CSV log not found: {csv_path}")

    df = pd.read_csv(csv_path)
    metric = args.metric
    train_col = metric
    val_col = f"val_{metric}"

    if train_col not in df.columns or val_col not in df.columns:
        raise KeyError(
            f"Columns not found for metric '{metric}'. "
            f"Available columns: {', '.join(df.columns)}"
        )

    plt.figure(figsize=(10, 6))
    plt.plot(df[train_col], label=f"train_{metric}")
    plt.plot(df[val_col], label=f"val_{metric}")
    plt.title(f"{metric} vs epoch")
    plt.xlabel("epoch")
    plt.ylabel(metric)
    plt.legend()
    plt.grid(True, alpha=0.25)
    plt.tight_layout()
    plt.show()


if __name__ == "__main__":
    main()
